Traceback (most recent call last):
  File "./trainsvm.py", line 165, in <module>
    main()
  File "./trainsvm.py", line 60, in main
    f = file(model_dir_path+'Forward_tr.save', 'rb')
IOError: [Errno 2] No such file or directory: '/cfs/zorn/nobackup/n/ngal/~ngal/MT/PythonCode/Models/5x1024_pr_225/Forward_tr.save'
